language: java
jdk:
  - oraclejdk8
sudo: false

install:
- mvn -N io.takari:maven:wrapper
#- mvn clean verify 


before_script: bash ./run_getjarlib.sh && ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V  &&  ls -lR target/

script:   bash parsetab.sh
