language: java
jdk:
  - oraclejdk8
sudo: false

install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_script: mvn clean verify

script: mkdir bin && cp target/*jar ./bin/ && bash parsetab.sh
